package cn.free.bean;
// Generated 2016-9-18 3:49:57 by Hibernate Tools 5.1.0.Beta1

import java.util.Date;

/**
 * Devicetype generated by hbm2java
 */
public class Devicetype implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 2238407308299828659L;
	private Integer id;
	private Integer userId;
	private String deviceType;
	private String lastIp;
	private String lastLocation;
	private Date lastTime;
	private String info;

	public Devicetype() {
	}

	public Devicetype(Integer userId, String deviceType, String lastIp, String lastLocation, Date lastTime,
			String info) {
		this.userId = userId;
		this.deviceType = deviceType;
		this.lastIp = lastIp;
		this.lastLocation = lastLocation;
		this.lastTime = lastTime;
		this.info = info;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Integer getUserId() {
		return this.userId;
	}

	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	public String getDeviceType() {
		return this.deviceType;
	}

	public void setDeviceType(String deviceType) {
		this.deviceType = deviceType;
	}

	public String getLastIp() {
		return this.lastIp;
	}

	public void setLastIp(String lastIp) {
		this.lastIp = lastIp;
	}

	public String getLastLocation() {
		return this.lastLocation;
	}

	public void setLastLocation(String lastLocation) {
		this.lastLocation = lastLocation;
	}

	public Date getLastTime() {
		return this.lastTime;
	}

	public void setLastTime(Date lastTime) {
		this.lastTime = lastTime;
	}

	public String getInfo() {
		return this.info;
	}

	public void setInfo(String info) {
		this.info = info;
	}

}
