package cn.free.bean;
// Generated 2016-9-18 3:49:57 by Hibernate Tools 5.1.0.Beta1

import java.util.Date;

/**
 * Note generated by hbm2java
 */
public class Note implements java.io.Serializable {

	private Integer id;
	private int userId;
	private String userName;
	private String title;
	private String info;
	private String content;
	private Date time;

	public Note() {
	}

	public Note(int userId, String title) {
		this.userId = userId;
		this.title = title;
	}

	public Note(int userId, String userName, String title, String info, String content, Date time) {
		this.userId = userId;
		this.userName = userName;
		this.title = title;
		this.info = info;
		this.content = content;
		this.time = time;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public int getUserId() {
		return this.userId;
	}

	public void setUserId(int userId) {
		this.userId = userId;
	}

	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public String getInfo() {
		return this.info;
	}

	public void setInfo(String info) {
		this.info = info;
	}

	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	public Date getTime() {
		return this.time;
	}

	public void setTime(Date time) {
		this.time = time;
	}

}
