package cn.free.bean;
// Generated 2016-9-18 3:49:57 by Hibernate Tools 5.1.0.Beta1

/**
 * User generated by hbm2java
 */
public class User implements java.io.Serializable {

	private Integer id;
	private String account;
	private String password;
	private String mobile;
	private String token;
	private String headImg;
	private String EMail;
	private String info;
	private String isDel;

	public User() {
	}

	public User(String account, String password, String mobile, String token, String headImg, String EMail, String info,
			String isDel) {
		this.account = account;
		this.password = password;
		this.mobile = mobile;
		this.token = token;
		this.headImg = headImg;
		this.EMail = EMail;
		this.info = info;
		this.isDel = isDel;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getAccount() {
		return this.account;
	}

	public void setAccount(String account) {
		this.account = account;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getMobile() {
		return this.mobile;
	}

	public void setMobile(String mobile) {
		this.mobile = mobile;
	}

	public String getToken() {
		return this.token;
	}

	public void setToken(String token) {
		this.token = token;
	}

	public String getHeadImg() {
		return this.headImg;
	}

	public void setHeadImg(String headImg) {
		this.headImg = headImg;
	}

	public String getEMail() {
		return this.EMail;
	}

	public void setEMail(String EMail) {
		this.EMail = EMail;
	}

	public String getInfo() {
		return this.info;
	}

	public void setInfo(String info) {
		this.info = info;
	}

	public String getIsDel() {
		return this.isDel;
	}

	public void setIsDel(String isDel) {
		this.isDel = isDel;
	}

}
